ignoreWorkspaceRootCheck: true
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - docs

onlyBuiltDependencies:
  - esbuild
  - rolldown
  - simple-git-hooks

overrides:
  vite: https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-core@1856
  vitest: 4.1.9
minimumReleaseAge: 60
minimumReleaseAgeExclude:
  - '@voidzero-dev/*'
  - vite-plus
  - '@vitest/*'
  - vite
  - vitest
  - '@oxc-project/*'
  - '@oxlint/*'
  - oxlint
  - oxfmt
  - oxlint-tsgolint
blockExoticSubdeps: false
